site_name: 'CUEH ComSec'
site_url: 'https://cov-comsec.github.io/'
site_author: 'CUEH ComSec'
site_description: 'The official site for Coventry University Ethical Hacking Computer Security Society (CUEH ComSec), find our latest presentations, videos & announcements!'
docs_dir: docs
nav:
  - Home: index.md
  - Week 1 - Nmap: 
      - Materials: w1-nmap/index.md
      - Writeup: w1-nmap/writeup.md
  - Week 2 - Web Enumeration:
    - Materials: w2-webenum/index.md
    - Writeup: w2-webenum/writeup.md
  - Week 3 - Ziemni, Graduate Talk: w3-ziemni/index.md
  - Week 4 - Web Exploitation: w4-webexploit/index.md

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - footnotes
  - mdx_math
  - attr_list

plugins:
  - search
  - macros:

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  
theme: 
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'logo.png'
  favicon: 'logo.png'
extra_css:
    - css/extra.css

